export const ADD_DECORATION = "ADD_DECORATION";
export const REMOVE_DECORATION = "REMOVE_DECORATION";
export const UPDATE_PURCHASABLE = "UPDATE_PURCHASABLE";

export const RESET_DECORATIONS = "RESET_DECORATIONS";


export const LOAD_BOOKS = "LOAD_BOOKS";
export const BOOK_LOAD_FAILED = "BOOK_LOAD_FAILED";


export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOGOUT = "AUTH_LOGOUT";